### ISSUE TITLE
[BUG] VITE_API_URL for UI doesn't work

### ISSUE THREAD

**Issue by luginbash** [steel-dev/steel-browser#99]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed in our [Discord server](https://discord.gg/steel-dev).

**Describe the bug**
I have set `VITE_API_URL` for my container, but when opening with a browser it still using localhost:3000

**To Reproduce**
1. use following compose.yml as tempalte
  ```
  services:
    api:
      image: ghcr.io/steel-dev/steel-browser-api:latest
      volumes:
        - ./.cache:/app/.cache
    ui:
      image: ghcr.io/steel-dev/steel-browser-ui:latest
      ports:
        - "3001:3000" # just a bit different from default/embedded VITE_API_URL baked into the image
      environment:
        - VITE_API_URL=https://<domain for api>
        - VITE_WS_URL=wss://<domain for api>
  ```
2. edit the compose file, use whatever for <domain for api>
4. docker compose up and browse localhost:3001
5. inspect elements -> Network
**Expected behavior**
ui should try to connect to VITE_API_URL instead of localhost:3000/v1/sessions

**Screenshots**

browser:

<img width="1230" alt="Image" src="https://github.com/user-attachments/assets/31485a21-13a1-4eeb-98ea-4bd542fa7c37" />

compose.yml:

<img width="697" alt="Image" src="https://github.com/user-attachments/assets/aa859fa7-a11d-4bf0-838a-2a4ae0217f48" />

_no need to worry about the *.in.lug.sh, they are local._

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Firefox, Vivaldi, LibreWolf
 - Version latest

**Additional context**
